apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd-agent
spec:
  # Disable the server on the workload cluster
  server:
    enabled: false

  # ArgoCD Agent configuration
  argoCDAgent:
    agent:
      # Enable the Agent component
      enabled: true

      # Credential method for authentication (mTLS)
      creds: "mtls:any"
      # Log level for the Agent component
      logLevel: "info"
      # Log format (text or json)
      logFormat: "text"
      # Container image for the ArgoCD Agent
      image: "quay.io/argoprojlabs/argocd-agent:v0.6.0"
      # Environment variables for the Agent component
      env:
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: "99"
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: "info"
        - name: GODEBUG
          value: "http2debug=2"

      # Client configuration for the Agent component
      client:
        # Address of the principal server to connect to
        # Update this to point to your principal server
        principalServerAddress: "argocd-agent-principal.example.com"
        # Port of the principal server
        principalServerPort: "443"
        # Operational mode (autonomous or managed)
        mode: "managed"
        # Enable WebSocket for real-time event streaming
        enableWebSocket: false
        # Enable compression for gRPC communication
        enableCompression: false
        # Keep-alive interval for pings to the principal
        keepAliveInterval: "30s"

      # TLS configuration for the agent
      tls:
        # Secret containing the agent client TLS certificate
        secretName: "argocd-agent-client-tls"
        # Secret containing the root CA certificate
        rootCASecretName: "argocd-agent-ca"
        # Skip TLS certificate validation (insecure, for development only)
        insecure: false

      # Redis configuration for caching and state management
      redis:
        # Redis server address
        serverAddress: "argocd-redis:6379"
