version: "2"
linters:
  enable:
    - ginkgolinter   # https://github.com/nunnatsa/ginkgolinter
    - govet
    - unused
    - ineffassign
    - unconvert
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vendor/
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/argoproj-labs/argocd-operator
  exclusions:
    generated: lax
    paths:
      - vendor/
      - third_party$
      - builtin$
      - examples$
