run:
  timeout: 2m
linters:
  enable:
    - govet
    - unused
    - goimports
    - ineffassign
    - unconvert
    - unparam
issues:
  exclude-files:
    - ".*_test\\.go"
  exclude-dirs:
    - vendor/
linters-settings:
  goimports:
    local-prefixes: github.com/argoproj-labs/argocd-operator
