resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:a09814522a72864cc10ec1be2834db63593427a9ab4779d97687a73dd30272f4
  name: controller
  newName: quay.io/argoprojlabs/argocd-operator
