resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:d547d9d09d0386694508d42f65a298e448a3c3045ed94251f6f6162aff2345b3
  name: controller
  newName: quay.io/argoprojlabs/argocd-operator
