apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: controller-manager
  name: argocd-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: 8080
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
