{
 "title": "Operator",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Reconcile Success",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "controller_runtime_reconcile_total{service=\"argocd-operator-metrics\", result=\"success\"}"
    }
   ]
  },
  {
   "title": "Reconcile Errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "controller_runtime_reconcile_total{result=\"error\"}"
    }
   ]
  },
  {
   "title": "Work Queue Retries",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "workqueue_retries_total{service=\"argocd-operator-metrics\"}"
    }
   ]
  },
  {
   "title": "REST Client Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rest_client_requests_total{service=\"argocd-operator-metrics\"}",
     "legendFormat": "{{method}}: Response: {{code}}"
    }
   ]
  }
 ]
}