#!/bin/sh

# General vars
export ARGOCD_OPERATOR_NAME=${ARGOCD_OPERATOR_NAME:-"argocd-operator"}
export QUAY_LOGIN_URL=${QUAY_LOGIN_URL:-"https://quay.io/cnr/api/v1/users/login"}

# Container image vars
export ARGOCD_OPERATOR_IMAGE_REPO=${ARGOCD_OPERATOR_IMAGE_REPO:-"quay.io/jmckind/${ARGOCD_OPERATOR_NAME}"}
export ARGOCD_OPERATOR_IMAGE_TAG=${ARGOCD_OPERATOR_IMAGE_TAG:-"latest"}
export ARGOCD_OPERATOR_IMAGE=${ARGOCD_OPERATOR_IMAGE:-"${ARGOCD_OPERATOR_REPO}:${ARGOCD_OPERATOR_TAG}"}

# Operator bundle vars
export ARGOCD_OPERATOR_BUNDLE_DIR=${ARGOCD_OPERATOR_BUNDLE_DIR:-"deploy/olm-catalog/${ARGOCD_OPERATOR_NAME}"}
export ARGOCD_OPERATOR_BUNDLE_NAMESPACE=${ARGOCD_OPERATOR_BUNDLE_NAMESPACE:-"john_mckenzie"}
export ARGOCD_OPERATOR_BUNDLE_REPO=${ARGOCD_OPERATOR_BUNDLE_REPO:-"${ARGOCD_OPERATOR_NAME}"}
export ARGOCD_OPERATOR_BUNDLE_RELEASE=${ARGOCD_OPERATOR_BUNDLE_RELEASE:-"0.0.0"}

# Misc
export GO111MODULE=on
