apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
spec:
  sourceType: grpc
  image: quay.io/argoprojlabs/argocd-operator-registry@sha256:5f8c80ecf90453e8dcbdc448bcf486ec94748cad4e98ca4e72c49fa618ca217d # 0.19.0
  displayName: Argo CD Operators
  publisher: Argo CD Community