apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
spec:
  sourceType: grpc
  image: quay.io/argoprojlabs/argocd-operator-registry@sha256:53e38e0c6d141faa5fbdaafe99339da62bccb537a46bea369ab82a20e158055a # 0.18.0
  displayName: Argo CD Operators
  publisher: Argo CD Community