// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	autoscalingv1 "k8s.io/api/autoscaling/v1"
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCD) DeepCopyInto(out *ArgoCD) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCD.
func (in *ArgoCD) DeepCopy() *ArgoCD {
	if in == nil {
		return nil
	}
	out := new(ArgoCD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArgoCD) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDApplicationControllerProcessorsSpec) DeepCopyInto(out *ArgoCDApplicationControllerProcessorsSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDApplicationControllerProcessorsSpec.
func (in *ArgoCDApplicationControllerProcessorsSpec) DeepCopy() *ArgoCDApplicationControllerProcessorsSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDApplicationControllerProcessorsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDApplicationControllerSpec) DeepCopyInto(out *ArgoCDApplicationControllerSpec) {
	*out = *in
	out.Processors = in.Processors
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDApplicationControllerSpec.
func (in *ArgoCDApplicationControllerSpec) DeepCopy() *ArgoCDApplicationControllerSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDApplicationControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDCASpec) DeepCopyInto(out *ArgoCDCASpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDCASpec.
func (in *ArgoCDCASpec) DeepCopy() *ArgoCDCASpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDCASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDCertificateSpec) DeepCopyInto(out *ArgoCDCertificateSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDCertificateSpec.
func (in *ArgoCDCertificateSpec) DeepCopy() *ArgoCDCertificateSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDCertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDDexOAuthSpec) DeepCopyInto(out *ArgoCDDexOAuthSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDDexOAuthSpec.
func (in *ArgoCDDexOAuthSpec) DeepCopy() *ArgoCDDexOAuthSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDDexOAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDDexSpec) DeepCopyInto(out *ArgoCDDexSpec) {
	*out = *in
	if in.OAuth != nil {
		in, out := &in.OAuth, &out.OAuth
		*out = new(ArgoCDDexOAuthSpec)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDDexSpec.
func (in *ArgoCDDexSpec) DeepCopy() *ArgoCDDexSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDDexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDExport) DeepCopyInto(out *ArgoCDExport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDExport.
func (in *ArgoCDExport) DeepCopy() *ArgoCDExport {
	if in == nil {
		return nil
	}
	out := new(ArgoCDExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArgoCDExport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDExportList) DeepCopyInto(out *ArgoCDExportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArgoCDExport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDExportList.
func (in *ArgoCDExportList) DeepCopy() *ArgoCDExportList {
	if in == nil {
		return nil
	}
	out := new(ArgoCDExportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArgoCDExportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDExportLocalStorageSpec) DeepCopyInto(out *ArgoCDExportLocalStorageSpec) {
	*out = *in
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(v1.PersistentVolumeClaimSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDExportLocalStorageSpec.
func (in *ArgoCDExportLocalStorageSpec) DeepCopy() *ArgoCDExportLocalStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDExportLocalStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDExportSpec) DeepCopyInto(out *ArgoCDExportSpec) {
	*out = *in
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(ArgoCDExportStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDExportSpec.
func (in *ArgoCDExportSpec) DeepCopy() *ArgoCDExportSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDExportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDExportStatus) DeepCopyInto(out *ArgoCDExportStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDExportStatus.
func (in *ArgoCDExportStatus) DeepCopy() *ArgoCDExportStatus {
	if in == nil {
		return nil
	}
	out := new(ArgoCDExportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDExportStorageSpec) DeepCopyInto(out *ArgoCDExportStorageSpec) {
	*out = *in
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(ArgoCDExportLocalStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDExportStorageSpec.
func (in *ArgoCDExportStorageSpec) DeepCopy() *ArgoCDExportStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDExportStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDGrafanaSpec) DeepCopyInto(out *ArgoCDGrafanaSpec) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDGrafanaSpec.
func (in *ArgoCDGrafanaSpec) DeepCopy() *ArgoCDGrafanaSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDGrafanaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDImportSpec) DeepCopyInto(out *ArgoCDImportSpec) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDImportSpec.
func (in *ArgoCDImportSpec) DeepCopy() *ArgoCDImportSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDImportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDIngressSpec) DeepCopyInto(out *ArgoCDIngressSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDIngressSpec.
func (in *ArgoCDIngressSpec) DeepCopy() *ArgoCDIngressSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDList) DeepCopyInto(out *ArgoCDList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArgoCD, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDList.
func (in *ArgoCDList) DeepCopy() *ArgoCDList {
	if in == nil {
		return nil
	}
	out := new(ArgoCDList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArgoCDList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDPrometheusSpec) DeepCopyInto(out *ArgoCDPrometheusSpec) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDPrometheusSpec.
func (in *ArgoCDPrometheusSpec) DeepCopy() *ArgoCDPrometheusSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDPrometheusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDRedisSpec) DeepCopyInto(out *ArgoCDRedisSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDRedisSpec.
func (in *ArgoCDRedisSpec) DeepCopy() *ArgoCDRedisSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDRedisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDServerAutoscaleSpec) DeepCopyInto(out *ArgoCDServerAutoscaleSpec) {
	*out = *in
	if in.HPA != nil {
		in, out := &in.HPA, &out.HPA
		*out = new(autoscalingv1.HorizontalPodAutoscalerSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDServerAutoscaleSpec.
func (in *ArgoCDServerAutoscaleSpec) DeepCopy() *ArgoCDServerAutoscaleSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDServerAutoscaleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDServerGRPCSpec) DeepCopyInto(out *ArgoCDServerGRPCSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDServerGRPCSpec.
func (in *ArgoCDServerGRPCSpec) DeepCopy() *ArgoCDServerGRPCSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDServerGRPCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDServerServiceSpec) DeepCopyInto(out *ArgoCDServerServiceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDServerServiceSpec.
func (in *ArgoCDServerServiceSpec) DeepCopy() *ArgoCDServerServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDServerServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDServerSpec) DeepCopyInto(out *ArgoCDServerSpec) {
	*out = *in
	in.Autoscale.DeepCopyInto(&out.Autoscale)
	out.GRPC = in.GRPC
	out.Service = in.Service
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDServerSpec.
func (in *ArgoCDServerSpec) DeepCopy() *ArgoCDServerSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDSpec) DeepCopyInto(out *ArgoCDSpec) {
	*out = *in
	out.Controller = in.Controller
	in.Dex.DeepCopyInto(&out.Dex)
	in.Grafana.DeepCopyInto(&out.Grafana)
	if in.Import != nil {
		in, out := &in.Import, &out.Import
		*out = new(ArgoCDImportSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	out.Redis = in.Redis
	in.Server.DeepCopyInto(&out.Server)
	out.TLS = in.TLS
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDSpec.
func (in *ArgoCDSpec) DeepCopy() *ArgoCDSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDStatus) DeepCopyInto(out *ArgoCDStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDStatus.
func (in *ArgoCDStatus) DeepCopy() *ArgoCDStatus {
	if in == nil {
		return nil
	}
	out := new(ArgoCDStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDTLSSpec) DeepCopyInto(out *ArgoCDTLSSpec) {
	*out = *in
	out.CA = in.CA
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDTLSSpec.
func (in *ArgoCDTLSSpec) DeepCopy() *ArgoCDTLSSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDTLSSpec)
	in.DeepCopyInto(out)
	return out
}
