apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: defaults
spec:
  image: argoproj/argocd
  version: v1.2.5
  controller:
    processors:
      operation: 10
      status: 20
  dex:
    image: quay.io/dexidp/dex
    version: v2.14.0
  grafana:
    enabled: false
    host: example-argocd-grafana
    image: grafana/grafana
    version: 6.4.2
  ingress:
    annotations: {}
    enabled: false
    path: /
  prometheus:
    enabled: false
    host: example-argocd-prometheus
    size: 1
  redis:
    image: redis
    version: 5.0.3
  server:
    grpc:
      host: example-argocd-grpc
    host: example-argocd
    insecure: false
    service:
      type: ClusterIP
  tls:
    ca:
      configMapName: example-argocd-ca
      secretName: example-argocd-ca
