apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: defaults
spec:
  applicationInstanceLabelKey: "mycompany.com/appname"
  configManagementPlugins: ""
  controller:
    processors:
      operation: 10
      status: 20
  dex:
    config: ""
    image: quay.io/dexidp/dex
    version: v2.21.0
    openShiftOAuth: false
  gaTrackingID: ""
  gaAnonymizeUsers: false
  grafana:
    enabled: false
    host: example-argocd-grafana
    image: grafana/grafana
    size: 1
    version: 6.5.1
  helpChatURL: "https://mycorp.slack.com/argo-cd"
  helpChatText: "Chat now!"
  image: argoproj/argocd
  import: {}
  ingress:
    annotations: {}
    enabled: false
    path: /
  kustomizeBuildOptions: ""
  oidcConfig: ""
  prometheus:
    enabled: false
    host: example-argocd-prometheus
    size: 1
  rbac:
    policy: ""
    defaultPolicy: "role:readonly"
    scopes: "[groups]"
  redis:
    image: redis
    version: 5.0.3
  repositories: ""
  resourceCustomizations: ""
  resourceExclusions: ""
  server:
    grpc:
      host: example-argocd-grpc
    host: example-argocd
    insecure: false
    service:
      type: ClusterIP
  statusBadgeEnabled: true
  tls:
    ca:
      configMapName: example-argocd-ca
      secretName: example-argocd-ca
  usersAnonymousEnabled: true
  version: v1.4.1
