apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: route
spec:
  sso:
    provider: keycloak
    verifyTLS: false
  server:
    ingress:
     enabled: true
    insecure: true