apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
spec:
  resourceIgnoreDifferences:
    all:
      jqPathExpressions:
          - xyz
          - abc
      jsonPointers:
          - xyz
          - abc
      managedFieldsManagers:
          - xyz
          - abc
    resourceIdentifiers:
      - group: apps
        kind: deployments
        customization:
          jqPathExpressions:
            - xyz
            - abc
          jsonPointers:
            - xyz
            - abc
          managedFieldManagers:
            - xyz
            - abc
      - group: batch
        kind: jobs
        customization:
          jqPathExpressions:
            - xyz
            - abc
          jsonPointers:
            - xyz
            - abc
          managedFieldsManagers:
            - xyz
            - abc
  resourceHealthChecks:
    - group: certmanager.k8s.io
      kind: Certificate
      check: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "Ready" and condition.status == "False" then
                hs.status = "Degraded"
                hs.message = condition.message
                return hs
              end
              if condition.type == "Ready" and condition.status == "True" then
                hs.status = "Healthy"
                hs.message = condition.message
                return hs
              end
            end
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for certificate"
        return hs
  resourceActions:
    - group: apps
      kind: Deployment
      action: |
        discovery.lua: |
        actions = {}
        actions["restart"] = {}
        return actions
        definitions:
        - name: restart
          # Lua Script to modify the obj
          action.lua: |
            local os = require("os")
            if obj.spec.template.metadata == nil then
                obj.spec.template.metadata = {}
            end
            if obj.spec.template.metadata.annotations == nil then
                obj.spec.template.metadata.annotations = {}
            end
            obj.spec.template.metadata.annotations["kubectl.kubernetes.io/restartedAt"] = os.date("!%Y-%m-%dT%XZ")
            return obj