name: Go

on:
  push:
    branches:
      - 'master'
      - 'release-*'
      - 'rhos-*'
  pull_request:
    paths-ignore:
      - "docs/**"
    branches:
      - 'master'
      - 'release-*'
      - 'rhos-*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Upload code coverage to codecov.io
      uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
      with:
        files: cover.out
        flags: unit-tests
        fail_ci_if_error: false
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
